### ISSUE TITLE
Add read_ole_metadata to module import

### ISSUE THREAD

**Issue by stefanengelmann** [data-exchange/dxchange#108]
Would it be possible to add the read_ole_metadata function to the __all__ list in reader.py such that the metadata can be read without the entire dataset? This is useful for me as I want to use metadata to load the dataset with memmap

**Comment by decarlof** [comment]
the txrm reader (the one using ole) was created without any help from Zeiss. There is no documentation about this file format. I will share this pull request with my contact at Zeiss to see if they can provide documentation. If they make this information available I will add modify the [current txrm meta data reader](https://github.com/data-exchange/dxchange/blob/b2a221ac8fb06db7bcc5b61c367a823e6b2ebde8/dxchange/reader.py#L513). I think is a very good idea.

**Comment by stefanengelmann** [comment]
I realised I could just type dxchange.reader.read_ole_metadata(), so never mind :)

**Comment by decarlof** [comment]
read_ole_metadata() only extract a limited and specific subset of meta data contained in the ole file. This is something I kind of reversed engineered from some txrm files I had. A general ole meta data reader should be something like read_hdf_meta() which relies on Hdf5MetadataReader(). This last class dives into the hdf file structure and extract all meta data available (as a python dictionary) without a priori knowledge of them. The ole meta data reader extract known label.
