### ISSUE TITLE
Version incompatible with the latest numpy

### ISSUE THREAD

**Issue by MingxuanGu** [data-exchange/dxchange#109]
`import dxchange` raises `"AttributeError: module 'numpy' has no attribute 'typeDict'"`.
As `np.typeDict` is deprecated since after `numpy=1.21`, the error occurs if `numpy` is up to date, or users can also keep the old version of `numpy`, but it may cause problems with other packages that adapt the latest `numpy`, which is very convenient to use. 
Could you please fix this? Many thanks!

**Comment by MingxuanGu** [comment]
Just found the solution. It can be resolved by updating the h5py package to the latest version.

**Comment by decarlof** [comment]
great!
