### ISSUE TITLE
New tag for dxchange?

### ISSUE THREAD

**Issue by ericdill** [data-exchange/dxchange#28]
I'm in the process of writing a recipe for tomopy (cc @dgursoy @licode ) to add to conda-forge and need to package this as part of that process.  Would it be possible to get a new tag on this project so I can point at something newer than October of 2014?

Thanks!

**Comment by decarlof** [comment]
done

**Comment by ericdill** [comment]
Thanks @decarlof :-D

**Comment by decarlof** [comment]
@ericdill please use @decarlof as maintainer
