### ISSUE TITLE
read_aps_32id needs to read theta if available in the file

### ISSUE THREAD

**Issue by decarlof** [data-exchange/dxchange#30]
check if theta was saved and if so read it from the hdf5 file and return it. If theta is missing return none.

**Comment by matze** [comment]
You do this now but it's [not documented](http://dxchange.readthedocs.io/en/latest/source/api/dxchange.exchange.html#dxchange.exchange.read_aps_32id) and breaking the [example](http://tomopy.readthedocs.io/en/latest/ipynb/tomopy.html).

**Comment by decarlof** [comment]
@matze thank you for pointing this out. I updated the dxchange docs in #41 and the tomopy docs in a separate pull request.

**Comment by decarlof** [comment]
@matze same [fix](https://github.com/tomopy/tomopy/pull/233) for tomopy.
