### ISSUE TITLE
Reading TXM and TXRM

### ISSUE THREAD

**Issue by teascavenger** [data-exchange/dxchange#36]
I have some TXM and TXRM files from Xradia. I was able to read TXRM file using reader.read_txrm but there is no TXM reader yet as far as I know. Is there a plan to make it any soon?

**Comment by decarlof** [comment]
@teascavenger Xradia uses XRM and TXRM (not TXM) file format. @skylarjhdownes implemented recently the XRM reader (see [pull request](https://github.com/data-exchange/dxchange/pull/33)) and he is now completing the TXRM format to support the APS 8-BM xradia instrument. @teascavenger be able to give you a more precise timeline

**Comment by teascavenger** [comment]
@decarlof that's correct. The raw data is saved as TXRM format. But the result of CT reconstruction made by some proprietary software of Xradia is saved as TXM.

**Comment by skylarjhdownes** [comment]
As far as I've been able to figure out, .txm files are essentially the same type of orm file structure as a .txrm, so read_txrm() ought to be able to read them.  I've added a read_txm() function which should be used in case we find it necessary to differentiate in the future.  See pull request #38.  I'm still pretty new to this repo- let me know if something isn't working as expected.

**Comment by teascavenger** [comment]
Thanks, Skylar. I will try using it soon. Will report back to you

Alex

----- Original Message -----

**Comment by skylarjhdownes** [comment]
After working with it a bit more, I'm sure my implementation was a bit screwey.  I've pushed a better one that's waiting in pull request #38.

**Comment by decarlof** [comment]
I closed #38. I was able to reconstruct full size xrm data collected at 26-ID. Very nice also the meta data exposure. This can now directly feed tomopy theta.

**Comment by skylarjhdownes** [comment]
#38 has been merged.

**Comment by michael-sutherland** [comment]
I think this issue has been resolved.
