### ISSUE TITLE
Dependency management

### ISSUE THREAD

**Issue by Dschoni** [data-exchange/dxchange#43]
I recently installed dxchange and saw, that it depends on the tifffile module. I saw nowhere, that there are any dependencies for dxchange on foreign modules and it doesn't seem to be handled automatically by the installer. Can this be changed?

**Comment by skylarjhdownes** [comment]
How did you install dxchange?  Tifffile is listed in the meta.yaml file as a runtime dependency, so as far as I know it _should_ install automatically if you install dxchange by running `conda install -c dgursoy dxchange`.

If you installed by pulling the source from Github, you probably have to install the dependencies listed in meta.yaml yourself, and we should probably have something in the docs about that...

**Comment by Dschoni** [comment]
We did install directly from source.

And yes, I think it would be a good idea, to put any dependencies in the readme close to the installing

instructions.

Thanks for your response!

________________________________
Von: Skylar Downes <notifications@github.com>
Gesendet: Donnerstag, 1. Dezember 2016 02:54
An: data-exchange/dxchange
Cc: Schock, Jonathan; Author
Betreff: Re: [data-exchange/dxchange] Dependency management (#43)


How did you install dxchange? Tifffile is listed in the meta.yaml file as a runtime dependency, so as far as I know it should install automatically if you install dxchange by running conda install -c dgursoy dxchange.

If you installed by pulling the source from Github, you probably have to install the dependencies listed in meta.yaml yourself, and we should probably have something in the docs about that...

-
