### ISSUE TITLE
Error encountered while reading XRM file

### ISSUE THREAD

**Issue by shehperd** [data-exchange/dxchange#58]
Hi, Many thanks for this library. I managed to install it and read the example data file **test_chip00.xrm** and **txrm_test_chip_tomo.txrm**. 
However, I encountered the following error while trying to read an XRM file, which was exported from Xradia software.
_UnboundLocalError: local variable 'arr' referenced before assignment_
Any idea on how to solve this issue?
An example XRM file can be found at [this link](https://www.dropbox.com/s/x2l8nedqq6fuath/Sample3Reference.xrm?dl=0).

**Comment by decarlof** [comment]
@shehperd please look if the issue is solved in the current version

**Comment by shehperd** [comment]
Many thanks, @decarlof . I tried the latest version, it can read my XRM file successfully.
Also, I tried using the _read_xrm()_ function to read TXM files (these are reconstructed images, as there is no function like read_txm). It didn't report error as well. Does this mean XRM and TXM files have the same structure?

**Comment by skylarjhdownes** [comment]
The xrm and txrm file formats _are_ essentially the same internally, the different extensions are only a convention to differentiate stacks from single images.

**Comment by shehperd** [comment]
Thanks for the explanation, @skylarjhdownes
