### ISSUE TITLE
asarray() no longer accepts memmap=True as a kwarg

### ISSUE THREAD

**Issue by alycejenni** [data-exchange/dxchange#61]
As of 2017-09-29 the `asarray()` method in [tifffile](https://www.lfd.uci.edu/~gohlke/code/tifffile.py.html) no longer accepts `memmap=True`. It now uses `out='memmap'`.

```python
arr = tifffile.imread(fname, memmap=True)
```

from reader.read_tiff() needs to be changed to:

```python
arr = tifffile.imread(fname, out='memmap')
```

**Comment by decarlof** [comment]
@alycejenni thanks for point this out!
