### ISSUE TITLE
Interpreting txrm meta data.

### ISSUE THREAD

**Issue by jakeoung** [data-exchange/dxchange#68]
This question may be too specific for txrm data. I am sorry if this question is not proper in this repository.

I want to reconstruct from txrm raw data using ASTRA toolbox. How can I know the distance between origin and detector and source? In the meta data, I got the following and I don't know how to get from this:

```
{'facility': None,
 'image_width': 1024,
 'image_height': 1024,
 'data_type': 5,
 'number_of_images': 1601,
 'pixel_size': 44.99769973754883,
 'reference_filename': b'\x00\x14...,
 'reference_data_type': 10,
 'thetas': array([-3.14149678, -3.13759498, -3.13380877, ...,  3.13378267,
         3.13758513,  3.1416089 ]),
 'x_positions': array([-1310.20007324,  -936.60003662, -1464.05004883, ..., -1247.09997559,
        -1401.        , -1036.80004883]),
 'y_positions': array([-31380.65039062, -31420.55078125, -31247.84960938, ...,
        -31515.75      , -31253.65039062, -31294.34960938]),
 'x-shifts': array([-0.05141851, -8.35447216,  3.36704612, ..., -1.39941931,
         2.02075362, -6.07303762]),
 'y-shifts': array([ 0.23718034, -0.64975119,  3.18803573, ..., -3.07316613,
         2.75161076,  1.84718478]),
 'reference': array([[ 960.06005859,  957.91125488,  959.35284424, ...,  868.76916504,...
```

**Comment by dgursoy** [comment]
Is this needed for a cone beam geometry?

**Comment by decarlof** [comment]
I believe the txrm reader in dxchange is for Xradia/Zeiss TXM and not for cone beam systems.
If you can share an example data sets we can add the missing meta data in the reader.

**Comment by jakeoung** [comment]
Thank you so much! I temporarily upload the raw txrm file here:
https://www.dropbox.com/s/7y7ca5pc9cv0xt8/dino_LFOV-80kV-air-2s.txrm?dl=0

From this raw data, I actually want to reconstruct 2D image using ASTRA toolbox (for example, I only use the middle row in the stacked images).

**Comment by jakeoung** [comment]
Any progress here? Or, if I want to do that myself, could you let me know how I can extract meta information myself..?

**Comment by decarlof** [comment]
If the meta data missing from our reader (like the distance between origin and detector and source) are included in your txrm file, you can add them to the reader as follows:

- List all meta data saved in your txrm file with:

```
import olefile

fname = 'dino_LFOV-80kV-air-2s.txrm'
ole = olefile.OleFileIO(fname)

for entry in ole.listdir():
    print(entry)
```

- Once you locate the missing meta data you can include them in our reader [module](https://github.com/data-exchange/dxchange/blob/master/dxchange/reader.py) by adding them in the meta_data dictionary defined in the read_ole_metadata(ole) function.

If you want these meta data to be part of the next release of dxchange please open a pull request.

**Comment by rockandsalt** [comment]
I have an even more basic question related to this. In the metadata, what do the x_position, y_position, the x_shift, the y_shift and the reference mean?
