### ISSUE TITLE
Convert .txm to .tiff

### ISSUE THREAD

**Issue by TomSemple** [data-exchange/dxchange#75]
Forgive me for the simple question, but can this program be used to convert TXM files from Zeiss/Xradia micro-CT scans to TIFF stacks?

I have practically no Python experience, but I thought it might be a relatively simple operation to read in TXM files and write out a TIFF stack. So I tried the following:

```
import tomopy
import dxchange

file_name = 'TLS575test.txm'

stack = dxchange.reader.read_txm(file_name)

dxchange.writer.write_tiff_stack(stack, 'test_tiff_output')
```

It appears to read the TXM file successfully, but then gives this error:
`AttributeError: 'tuple' object has no attribute 'shape'`

Am I even remotely on the right track, or way off?

Any tips would be greatly appreciated!

**Comment by data-exchange** [comment]
I often use data-exchange to convert different tomography data format into dxchange. So what you are trying to do is perfecly fine. The issue could be in the  txm data. If you can post a link fro m where I can download it I can check it out


On Nov 21, 2018, at 22:46, TomSemple <notifications@github.com<mailto:notifications@github.com>> wrote:


Forgive me for the simple question, but can this program be used to convert TXM files from Zeiss/Xradia micro-CT scans to TIFF stacks?

I have practically no Python experience, but I thought it might be a relatively simple operation to read in TXM files and write out a TIFF stack. So I tried the following:

import tomopy
import dxchange

file_name = 'TLS575test.txm'

stack = dxchange.reader.read_txm(file_name)

dxchange.writer.write_tiff_stack(stack, 'test_tiff_output')


It appears to read the TXM file successfully, but then gives this error:
AttributeError: 'tuple' object has no attribute 'shape'

Am I even remotely on the right track, or way off?

Any tips would be greatly appreciated!

**Comment by TomSemple** [comment]
Thanks for your reply!
Here is a link to one of my TXM files on Google Drive. 
https://drive.google.com/open?id=1ijtkev4dF70M8dVvlEIZaqyf9FloYRTM

**Comment by decarlof** [comment]
@TomSemple  read_txrm returns (data, metadata). This works as intended:

```
import dxchange
import dxchange.reader as dxreader

fname = '/Downloads/161006_TLS629_Curvothynnus_female_2.94um_head.txm'

# Read the APS 26-ID raw data.
data, metadata = dxreader.read_txrm(fname)

dxchange.write_tiff_stack(data, fname='/Downloads/recon')
```
